name: deploy app
on: 
    push:
        branches:
            - main
jobs:
  deployment:
    name: Deployment in server
    environment: 
      name: Deploy
      url: https://github.com
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app in server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME}}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd gladius.lionforge.com.br
            git pull
            php artisan migrate --force
            php artisan optimize