name: deploy app
on: 
    push:
        branches:
            - main
jobs:
  deployment:
    name: Deployment in server
    environment: 
      name: Deploy
      url: https://github.com
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app in server
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME}}
          pass: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd gladius.lionforge.com.br
            git pull
            php $composer install
            php artisan migrate --force
            php artisan optimize